"""initial schema with pgvector support

Revision ID: b45450486962
Revises:
Create Date: 2026-06-07 03:52:12.517715

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b45450486962"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("first_appearance", sa.String(length=255), nullable=True),
        sa.Column("appearance_frequency", sa.Integer(), nullable=True),
        sa.Column("embedding_vec", sa.Text(), nullable=True),
        sa.Column("embedding", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name", name="uix_canonical_name"),
    )
    op.create_index(
        op.f("ix_characters_canonical_name"), "characters", ["canonical_name"], unique=False
    )
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.Column("realm", sa.String(length=255), nullable=True),
        sa.Column("parent_location_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "type", name="uix_location_name_type"),
    )
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=False)
    op.create_table(
        "novels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("total_chapters", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title", "author", name="uix_novel_title_author"),
    )
    op.create_index(op.f("ix_novels_title"), "novels", ["title"], unique=False)
    op.create_table(
        "aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("alias_type", sa.String(length=100), nullable=False),
        sa.Column("alias_value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "alias_value", name="uix_character_alias"),
    )
    op.create_index(op.f("ix_aliases_alias_value"), "aliases", ["alias_value"], unique=False)
    op.create_table(
        "chapters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["novel_id"],
            ["novels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("novel_id", "chapter_number", name="uix_chapter_novel_number"),
    )
    op.create_table(
        "character_locations",
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("character_id", "location_id"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_org_id", sa.UUID(), nullable=True),
        sa.Column("headquarters_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["headquarters_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "type", name="uix_org_name_type"),
    )
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_table(
        "relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("related_character_id", sa.UUID(), nullable=False),
        sa.Column("relationship_type", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["related_character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "related_character_id", "relationship_type", name="uix_relationship"
        ),
    )
    op.create_table(
        "titles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "title", name="uix_character_title"),
    )
    op.create_index(op.f("ix_titles_title"), "titles", ["title"], unique=False)
    op.create_table(
        "character_organizations",
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("character_id", "organization_id"),
    )
    op.create_table(
        "organization_relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("related_organization_id", sa.UUID(), nullable=False),
        sa.Column("relationship_type", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["related_organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "related_organization_id",
            "relationship_type",
            name="uix_org_relationship",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_relationships")
    op.drop_table("character_organizations")
    op.drop_index(op.f("ix_titles_title"), table_name="titles")
    op.drop_table("titles")
    op.drop_table("relationships")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_table("character_locations")
    op.drop_table("chapters")
    op.drop_index(op.f("ix_aliases_alias_value"), table_name="aliases")
    op.drop_table("aliases")
    op.drop_index(op.f("ix_novels_title"), table_name="novels")
    op.drop_table("novels")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_index(op.f("ix_characters_canonical_name"), table_name="characters")
    op.drop_table("characters")
    # ### end Alembic commands ###
